# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurants', '0005_auto_20171004_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sube',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subereview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subereview',
            name='sube',
        ),
        migrations.RemoveField(
            model_name='subereview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sube',
        ),
        migrations.DeleteModel(
            name='SubeReview',
        ),
    ]
